#!/usr/bin/env python3
"""Table-driven generator for the KC868-A6 Kospel master firmware.
CONTROLS -> template number (write func16, byte-swapped) + read-back sensor.
SELECTS  -> template select (writes index) + read-back sensor.
Every write is verifiable live. Grows toward full C.MI parity."""

HEAD = '''# KC868-A6 V1.3 — Kospel EKCO.MN3 + C.MG3 RS485 MASTER (generated by gen_master.py).
# Modbus RTU 9600 8N1; heater 0x65, C.MG3 0x69; reads func03, writes func16, values LE.
# Run ONLY with the C.MI removed from the bus.
substitutions:
  name: kc868-heater
esphome:
  name: ${name}
  includes:
    - wifi_scan_inc.h   # pulls <esp_wifi.h> into main so the scan-button lambda compiles
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
  baud_rate: 115200
api:
  encryption:
    key: !secret api_key
  actions:
    # 24h max-power plan (idx 0..3 = 12/16/20/24 kW per LOCAL hour). enable=false stops steering
    # (the user's manual setting then stays untouched).
    - action: set_power_plan
      variables:
        plan: int[]
        floor: float
        cwu_min: float
        enable: bool
      then:
        - lambda: |-
            if (plan.size() < 24) return;
            for (int h = 0; h < 24; h++) id(pwr_plan)[h] = plan[h];
            id(pwr_floor) = floor;
            id(pwr_cwu_min) = cwu_min;
            id(pwr_enable) = enable;
            id(pwr_last) = millis();
            ESP_LOGI("pwrplan", "plan received (enable=%d floor=%.1f cwu_min=%.1f)", enable, floor, cwu_min);
    # ---- diagnostic raw Modbus access (reverse-engineering aid; result in the 'Modbus peek'
    # text sensor as "addr: v1 v2 ..." decimal, LE-decoded). USE WITH CARE — mb_write hits the
    # live heater. dev 0 = heater, 1 = C.MG3.
    - action: mb_read
      variables:
        addr: int
        count: int
        dev: int
      then:
        - lambda: |-
            if (!id(esp_owns_bus)) return;
            int n = count; if (n < 1) n = 1; if (n > 16) n = 16;
            uint16_t a = (uint16_t) addr;
            auto cb = [a](esphome::modbus::EntityType, uint16_t, std::span<const uint8_t> d) {
              std::string s = str_sprintf("0x%04X:", a);
              for (size_t i = 0; i + 1 < d.size(); i += 2)
                s += str_sprintf(" %u", (unsigned)((d[i+1] << 8) | d[i]));
              id(mb_peek).publish_state(s);
              ESP_LOGI("mbpeek", "%s", s.c_str());
            };
            auto *c = (dev == 1) ? id(cmg3) : id(heater);
            c->queue_command(esphome::modbus_controller::ModbusCommandItem::create_read_command(
                c, esphome::modbus_controller::ModbusRegisterType::HOLDING, a, (uint8_t) n, cb));
    # (mb_write intentionally removed — raw arbitrary writes are too dangerous; use the typed
    #  controls, which validate + gate. mb_read stays for read-only reverse-engineering.)
    # Daily-program editor (parity with the C.MI timetable pages). Rewrites one program's 5 time
    # slots as the 15-reg block [s1,e1,..,s5,e5, i1..i5] at `base` (min-since-midnight; idx 1=ochrona
    # 2=komfort 3=komfort- 4=komfort+; 65535=slot pusty). Bases: CO 0x0C1C, CWU 0x0C9E, cyrk 0x0D20
    # (heater); C.MG3 0x0B90. base = 0x0C1C + 15*(nr-1) for program nr.
    - action: set_daily_program_heater
      variables:
        base: int
        starts: int[]
        stops: int[]
        idxs: int[]
      then:
        - lambda: |-
            if(!id(esp_owns_bus)) return;
            if(starts.size()!=5||stops.size()!=5||idxs.size()!=5) return;
            std::vector<uint16_t> regs;
            for(int i=0;i<5;i++){ uint16_t s=(uint16_t)starts[i],e=(uint16_t)stops[i];
              regs.push_back(((s&0xFF)<<8)|(s>>8)); regs.push_back(((e&0xFF)<<8)|(e>>8)); }
            for(int i=0;i<5;i++){ uint16_t v=(uint16_t)idxs[i]; regs.push_back(((v&0xFF)<<8)|(v>>8)); }
            id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                id(heater),(uint16_t)base,15,regs));
    - action: set_daily_program_cmg3
      variables:
        base: int
        starts: int[]
        stops: int[]
        idxs: int[]
      then:
        - lambda: |-
            if(!id(esp_owns_bus)) return;
            if(starts.size()!=5||stops.size()!=5||idxs.size()!=5) return;
            std::vector<uint16_t> regs;
            for(int i=0;i<5;i++){ uint16_t s=(uint16_t)starts[i],e=(uint16_t)stops[i];
              regs.push_back(((s&0xFF)<<8)|(s>>8)); regs.push_back(((e&0xFF)<<8)|(e>>8)); }
            for(int i=0;i<5;i++){ uint16_t v=(uint16_t)idxs[i]; regs.push_back(((v&0xFF)<<8)|(v>>8)); }
            id(cmg3)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                id(cmg3),(uint16_t)base,15,regs));
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Stationary device at -60..-70 dBm: ESPHome 2026.7's post-connect roam scans (default on,
  # trigger below -49 dBm) go off-channel and reset all API/TCP connections every few minutes.
  post_connect_roaming: false
  # ESP32 default is 'light' (modem-sleep): on a weak link, sleeping through AP beacons causes
  # periodic disassociations (graph gaps) and 100-280 ms ping jitter. Mains-powered -> disable.
  power_save_mode: none
  # Static IP (no DHCP dependency; .221-.223 = the three ESPHome nodes). The MikroTik still
  # holds a stale .134 reservation for this MAC — harmless, device never DHCPs.
  manual_ip:                 # EDIT ME: your network
    static_ip: 192.168.1.221
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
  ap:
    ssid: "${name}-fallback"
    password: !secret fallback_ap_password
captive_portal:
# NTP time -> heater RTC. The C.MI kept the heater clock synced (needed for schedules/disinfection);
# the ESP now does it. Heater RTC lives at 0x0AF6..0x0AFC = sec,min,hour,dow(0=Mon),day,month,year-2000
# (little-endian, func16). Europe/Warsaw gives DST-correct local time -> keep heater auto-DST OFF.
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers: [pool.ntp.org, time.google.com]
    on_time_sync:
      - lambda: |-
          if(!id(esp_owns_bus)) return;
          auto t=id(sntp_time).now(); if(!t.is_valid()) return;
          auto sw=[](uint16_t v){return (uint16_t)(((v&0xFF)<<8)|(v>>8));};
          uint16_t dow=(uint16_t)(((int)t.day_of_week+5)%7);
          std::vector<uint16_t> w={sw((uint16_t)t.second),sw((uint16_t)t.minute),sw((uint16_t)t.hour),sw(dow),sw((uint16_t)t.day_of_month),sw((uint16_t)t.month),sw((uint16_t)(t.year-2000))};
          id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(id(heater),0x0AF6,7,w));
          ESP_LOGI("timesync","heater clock <- %04d-%02d-%02d %02d:%02d:%02d dow%d",t.year,t.month,t.day_of_month,t.hour,t.minute,t.second,(int)dow);
# Onboard I2C expanders: relays @0x24 (also inputs @0x22, RTC 0x68, OLED 0x3C present).
i2c:
  sda: GPIO4
  scl: GPIO15
  scan: false
pcf8574:
  - id: pcf_out
    address: 0x24
# Bus ownership: true = ESP masters the RS485; false = ESP is silent so the C.MI can master.
globals:
  - id: esp_owns_bus
    type: bool
    restore_value: no
    initial_value: 'true'
  # Write pending/confirm framework: a user-changed control keeps its NEW value (readback sync
  # suppressed) until the device confirms, reverts + reports after WP_TIMEOUT if it never applies.
  - id: wp_target
    type: float[96]
    restore_value: no
  - id: wp_until
    type: uint32_t[96]
    restore_value: no
  - id: wp_failed
    type: uint32_t[96]
    restore_value: no
  # 24h power plan (max-power index 0..3 per local hour), pushed by the AI via the API service
  # set_power_plan and executed HERE — heater has no native power schedule, and the plan must
  # keep working with HA down (same philosophy as the TRV window failsafe).
  - id: pwr_plan
    type: int[24]
    restore_value: no
  - id: pwr_floor
    type: float
    restore_value: no
    initial_value: '19'
  - id: pwr_cwu_min
    type: float
    restore_value: no
    initial_value: '35'
  - id: pwr_enable
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: pwr_last
    type: uint32_t
    restore_value: no
    initial_value: '0'
  # TRV bridge (Fibaro rooms via r730-gpu:8901 <- zwave-js on the RPi) — HA-independent failsafe data
  - id: trv_okna
    type: int
    restore_value: no
    initial_value: '-1'
  - id: trv_min_temp
    type: float
    restore_value: no
    initial_value: 'NAN'
  - id: trv_last_ok
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: trv_lato_flag
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: trv_okna_since
    type: uint32_t
    restore_value: no
    initial_value: '0'
  - id: trv_closed_since
    type: uint32_t
    restore_value: no
    initial_value: '0'
# TRV data arrives as UDP push from the .80 zwave agent (30 s cadence). The previous
# http_request pull PROVEN to kill the HA API connection on ~1 in 2-10 polls (blip intervals
# quantized exactly to the poll period; 60s->127s experiment 2026-08-29). UDP cannot do that.
udp:
  port: 8902
  on_receive:
    then:
      - lambda: |-
          std::string body((const char*) data.data(), data.size());
          json::parse_json(body, [](JsonObject root) -> bool {
            if (root["okna"].is<int>()) id(trv_okna) = root["okna"].as<int>();
            if (root["min_temp"].is<float>()) id(trv_min_temp) = root["min_temp"].as<float>();
            id(trv_last_ok) = millis();
            return true;
          });
json:
uart:
  - id: rs485
    tx_pin: GPIO27
    rx_pin: GPIO14
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1
modbus:
  id: modbus_bus
  uart_id: rs485
  send_wait_time: 1000ms   # was 2000ms default; fail unresponsive reads faster so the queue drains
# Auto-polling (stable). The bus-owner switch pauses/resumes these via stop_poller()/start_poller()
# so the ESP goes fully silent when the C.MI takes the bus (no manual-update queue pileups).
modbus_controller:
  - id: heater
    address: 101
    modbus_id: modbus_bus
    update_interval: 10s
    command_throttle: 100ms
  - id: cmg3
    address: 105
    modbus_id: modbus_bus
    update_interval: 30s
    command_throttle: 150ms
'''

MON = [
 (0x0B48,"co_inlet_temp","Heater CO inlet temp",0.1,True,"°C","temperature"),
 (0x0B49,"co_outlet_temp","Heater CO outlet temp",0.1,True,"°C","temperature"),
 (0x0B44,"factor_temp","Heater factor temp",0.1,True,"°C","temperature"),
 (0x0B4B,"room_temp","Heater room temp",0.1,True,"°C","temperature"),
 (0x0B4A,"dhw_temp","Heater DHW temp",0.1,True,"°C","temperature"),
 (0x0B4C,"outside_temp","Heater outside temp",0.1,True,"°C","temperature"),
 (0x0B46,"power_now","Heater power now",0.1,False,"kW","power"),
 (0x0B4E,"water_pressure","Heater water pressure",0.01,False,"bar","pressure"),
 (0x0B4F,"water_flow","Heater water flow",0.1,False,"L/min",None),
 (0x0B8C,"boiler_supply_ro","Heater boiler supply temp",0.1,False,"°C","temperature"),
 (0x0B75,"room_hysteresis_ro","Heater room hysteresis",0.1,False,"°C",None),
 # Anti-legionella / disinfection (Dezynfekcja) — DHW-tank programme (confirmed live 2026-08-26).
 # temp (0x0B76) + duration (0x0B79) are writable CONTROLS below; day+start stay read-only w/ text.
 (0x0B77,"disinfection_day","Dezynfekcja dzień (0=Pn)",1,False,None,None),
 (0x0B78,"disinfection_start_min","Dezynfekcja start (min od północy)",1,False,"min",None),
 # Heater RTC readback (to see the NTP-synced clock). 0x0AF7 min, 0x0AF8 hour.
 (0x0AF8,"heater_rtc_hour","Heater RTC hour",1,False,None,None),
 (0x0AF7,"heater_rtc_min","Heater RTC minute",1,False,None,None),
]
RAWDIAG = [(0x0B55,"mode_word","Heater mode word"),(0x0B52,"error_code","Heater error code"),
           (0x0B51,"status_word","Heater status word"),
           (0x0B54,"config2_word","Heater config2 word"),
           (0x0B58,"pump_type_ro","Heater pump type raw (0=Grundfos 1=Wilo)"),
           (0x0B82,"pump_regulation_ro","Heater pump regulation raw (0=var 1=const dp)"),
           (0x0B83,"pump_lift_ro","Heater pump lift index raw")]
STATUS_BITS=[("pump",0),("circulation",1),("valve",2),("relay_rp",4),("functional_input_active",6),
             ("co_demand",7),("dhw_demand",8)]  # 0x0B51 bit7=CO grzeje, bit8=CWU grzeje
MODE_BITS=[("summer",3),("dhw_enabled",4),("winter",5),("party",6),("vacation",7),("manual",9),
           ("thermostat",2),("turbo",11),("pump_auto",8),("room_control",15)]

# CONTROLS: (dev, reg, id, name, vmin, vmax, step, scale, unit) scale=10 => x*10 stored
CONTROLS = [
 ("heater",0x0B62,"max_power_index","Heater max-power index",0,3,1,1,None),
 ("heater",0x0B8D,"manual_setpoint","Heater manual setpoint",5,80,0.5,10,"°C"),
 # Group A
 ("heater",0x0B66,"dhw_economic","Heater DHW economic temp",30,80,0.5,10,"°C"),
 ("heater",0x0B67,"dhw_comfort","Heater DHW comfort temp",30,80,0.5,10,"°C"),
 ("heater",0x0B68,"room_economic","Heater room economic temp",5,35,0.1,10,"°C"),
 ("heater",0x0B69,"room_comfort_minus","Heater room comfort minus temp",5,35,0.1,10,"°C"),
 ("heater",0x0B6A,"room_comfort","Heater room comfort temp",5,35,0.1,10,"°C"),
 ("heater",0x0B6B,"room_comfort_plus","Heater room comfort plus temp",5,35,0.1,10,"°C"),
 ("heater",0x0B7B,"co_temp_max","Heater CO max temp",20,85,0.5,10,"°C"),
 ("heater",0x0B73,"co_temp_manual","Heater CO manual temp",20,85,0.5,10,"°C"),
 ("heater",0x0B74,"co_temp_outside_off","Heater CO outside-off temp",0,40,0.5,10,"°C"),
 ("heater",0x0B71,"co_curve_number","Heater CO heating-curve number",0,20,1,1,None),
 # Group B1: service config direct-write values
 ("heater",0x0B59,"pump_protection_time","Heater pump protection time",0,1440,1,1,"min"),
 ("heater",0x0B81,"turbo_hysteresis","Heater turbo hysteresis",0.1,10,0.1,10,"°C"),
 ("heater",0x0B72,"co_curve_offset","Heater CO curve offset",-10,10,0.5,10,"°C"),
 # Disinfection schedule params (plain writes; day+start read-only above). Flags on 0x0B54 -> switches.
 ("heater",0x0B76,"disinfection_temp","Dezynfekcja temp. docelowa",40,75,0.5,10,"°C"),
 ("heater",0x0B79,"disinfection_duration","Dezynfekcja czas trwania",5,180,5,1,"min"),
 # C.MG3 (0x69) — writable via ESP (auto-poll). curve_number/max_supply/hand_temp hold as plain
 # single writes. curve_shift (0x0B61) latches ONLY when bundled with curve_number+flag -> handled
 # by CMG3_CURVE_BUNDLE below, not here. C.MG3 rejects wide reads -> force_new_range.
 ("cmg3",0x0B60,"cmg3_curve_number","C.MG3 heating curve number",0,20,1,1,None),
 ("cmg3",0x0B61,"cmg3_curve_shift","C.MG3 heating curve shift",-5,5,0.5,10,"°C"),
 ("cmg3",0x0B57,"cmg3_max_supply","C.MG3 max circuit supply",20,80,0.5,10,"°C"),
 ("cmg3",0x0B5B,"cmg3_hand_temp","C.MG3 hand temperature",5,35,0.5,10,"°C"),
 ("cmg3",0x0B5C,"cmg3_pump_protect","C.MG3 czas ochrony pompy",0,1440,1,1,"min"),
 ("cmg3",0x0B63,"cmg3_hysteresis","C.MG3 histereza temp. pokojowej",0.1,10,0.1,10,"°C"),
 # CH weekly program assignment (which daily program 1-8 each weekday uses). 0x0C94..0x0C9A = Mon..Sun.
 # TEST: are these directly writable, or do they need the symbolic CH_TIMETABLE gate?
 ("heater",0x0C94,"ch_prog_mon","Program CO — Poniedziałek",1,8,1,1,None),
 ("heater",0x0C95,"ch_prog_tue","Program CO — Wtorek",1,8,1,1,None),
 ("heater",0x0C96,"ch_prog_wed","Program CO — Środa",1,8,1,1,None),
 ("heater",0x0C97,"ch_prog_thu","Program CO — Czwartek",1,8,1,1,None),
 ("heater",0x0C98,"ch_prog_fri","Program CO — Piątek",1,8,1,1,None),
 ("heater",0x0C99,"ch_prog_sat","Program CO — Sobota",1,8,1,1,None),
 ("heater",0x0C9A,"ch_prog_sun","Program CO — Niedziela",1,8,1,1,None),
 # DHW/CWU weekly program assignment (0x0D16..0x0D1C = Mon..Sun). daily-program base 0x0C9E.
 ("heater",0x0D16,"dhw_prog_mon","Program CWU — Poniedziałek",1,8,1,1,None),
 ("heater",0x0D17,"dhw_prog_tue","Program CWU — Wtorek",1,8,1,1,None),
 ("heater",0x0D18,"dhw_prog_wed","Program CWU — Środa",1,8,1,1,None),
 ("heater",0x0D19,"dhw_prog_thu","Program CWU — Czwartek",1,8,1,1,None),
 ("heater",0x0D1A,"dhw_prog_fri","Program CWU — Piątek",1,8,1,1,None),
 ("heater",0x0D1B,"dhw_prog_sat","Program CWU — Sobota",1,8,1,1,None),
 ("heater",0x0D1C,"dhw_prog_sun","Program CWU — Niedziela",1,8,1,1,None),
 # Circulation weekly program assignment (0x0D98..0x0D9E = Mon..Sun). daily-program base 0x0D20.
 ("heater",0x0D98,"circ_prog_mon","Program cyrkulacji — Poniedziałek",1,8,1,1,None),
 ("heater",0x0D99,"circ_prog_tue","Program cyrkulacji — Wtorek",1,8,1,1,None),
 ("heater",0x0D9A,"circ_prog_wed","Program cyrkulacji — Środa",1,8,1,1,None),
 ("heater",0x0D9B,"circ_prog_thu","Program cyrkulacji — Czwartek",1,8,1,1,None),
 ("heater",0x0D9C,"circ_prog_fri","Program cyrkulacji — Piątek",1,8,1,1,None),
 ("heater",0x0D9D,"circ_prog_sat","Program cyrkulacji — Sobota",1,8,1,1,None),
 ("heater",0x0D9E,"circ_prog_sun","Program cyrkulacji — Niedziela",1,8,1,1,None),
 # C.MG3 circuit weekly program assignment (0x0C08..0x0C0E = Mon..Sun). daily-program base 0x0B90.
 ("cmg3",0x0C08,"cmg3_prog_mon","Program C.MG3 — Poniedziałek",1,8,1,1,None),
 ("cmg3",0x0C09,"cmg3_prog_tue","Program C.MG3 — Wtorek",1,8,1,1,None),
 ("cmg3",0x0C0A,"cmg3_prog_wed","Program C.MG3 — Środa",1,8,1,1,None),
 ("cmg3",0x0C0B,"cmg3_prog_thu","Program C.MG3 — Czwartek",1,8,1,1,None),
 ("cmg3",0x0C0C,"cmg3_prog_fri","Program C.MG3 — Piątek",1,8,1,1,None),
 ("cmg3",0x0C0D,"cmg3_prog_sat","Program C.MG3 — Sobota",1,8,1,1,None),
 ("cmg3",0x0C0E,"cmg3_prog_sun","Program C.MG3 — Niedziela",1,8,1,1,None),
]

# SELECTS: (dev, reg, id, name, [options])
SELECTS = [
 ("heater",0x0B7F,"functional_input","Heater functional input",["input 0","input 1","input 2"]),
 # Max power as user-facing kW (index 0..3 -> table 0x0B36.. = 120/160/200/240 => 12/16/20/24 kW).
 ("heater",0x0B62,"max_power_kw","Moc maksymalna",["12 kW","16 kW","20 kW","24 kW"]),
 # C.MG3 schedule type: 0x0B5F plain (0=outside/pogodowy, 1=inside/pokojowy).
 ("cmg3",0x0B5F,"cmg3_timetable_type","C.MG3 typ harmonogramu",["Pogodowy (zewn.)","Pokojowy (wewn.)"]),
 # Heater system topology (config_mode__save writes 0x0B8A plain): 0=basic,1=source,2=buffer.
 ("heater",0x0B8A,"operating_mode","Tryb pracy (system)",["Podstawowy","Źródło ciepła","Bufor"]),
]

# BITS: (reg, bit, id, name, base_sensor_id)  -> template switch (read-modify-write)
BITS = [] and [
 (0x0B55,0,"turbo_priority","Heater turbo priority","mode_word"),
 (0x0B55,1,"room_regulator","Heater room regulator mode","mode_word"),
 (0x0B55,2,"boiler_regulation","Heater boiler regulation","mode_word"),
 (0x0B55,4,"dhw_enable","Heater DHW enable","mode_word"),
 (0x0B55,8,"pump_auto","Heater pump auto","mode_word"),
 (0x0B55,11,"turbo","Heater turbo mode","mode_word"),
 (0x0B55,15,"room_control","Heater room control","mode_word"),
 (0x0B54,8,"pressure_control","Heater pressure control","config2_word"),
 (0x0B54,13,"pump_venting","Heater pump venting","config2_word"),
]

def swap_signed(scale, fault):
    l=["- lambda: |-",
       "          uint16_t v=(uint16_t)x; v=((v&0xFF)<<8)|(v>>8); int16_t s=(int16_t)v;"]
    if fault: l.append("          if (s <= -1000) return NAN;")
    l.append(f"          return s * {float(scale)}f;")   # float() so scale=1 -> 1.0f (valid literal)
    return "\n        ".join(l)
def swap_uint():
    return "- lambda: |-\n          uint16_t v=(uint16_t)x; return ((v&0xFF)<<8)|(v>>8);"

# Human-readable TEXT sensors (like the C.MI showed), published from source registers.
TEXT_SENSORS=[
 ("op_mode_text","Heater operating mode"),
 ("status_text","Heater status"),
 ("error_text","Heater error"),
 ("pump_type_text","Heater pump type"),
 ("pump_reg_text","Heater pump regulation"),
 ("pump_lift_text","Heater pump lift"),
 ("disinfection_day_text","Dezynfekcja dzień tygodnia"),
 ("disinfection_start_text","Dezynfekcja godzina startu"),
 ("heater_clock_text","Zegar kotła (RTC)"),
 ("wp_pending_text","Zapisy w toku"),
 ("wp_failed_text","Zapisy nieudane"),
 ("wifi_scan_result","Skan WiFi"),
 ("mb_peek","Modbus peek"),
]
# on_value C++ body per source sensor id -> publishes the friendly text (and mode select sync)
TEXTHOOKS={
 "mode_word":'''uint16_t m=(uint16_t)x;
if ((m>>5)&1) id(heater_mode).publish_state("winter");
else if ((m>>3)&1) id(heater_mode).publish_state("summer");
else id(heater_mode).publish_state("off");
std::string t = ((m>>5)&1)?"Zima":(((m>>3)&1)?"Lato":"Wyłączony");
if((m>>9)&1) t+=" · Ręczny";
if((m>>11)&1) t+=" · Turbo";
if((m>>6)&1) t+=" · Party";
if((m>>7)&1) t+=" · Urlop";
id(op_mode_text).publish_state(t);
id(pump_auto_ctl).publish_state(((m>>8)&1)!=0);
id(cfg_antifrost_ctl).publish_state(((m>>12)&1)!=0);
id(cfg_co_curve_ctl).publish_state(((m>>14)&1)!=0);
id(cfg_tank_enable_ctl).publish_state(((m>>4)&1)!=0);
id(cfg_dhw_int_ctl).publish_state(((m>>2)&1)!=0);
id(cfg_room_int_ctl).publish_state(((m>>1)&1)!=0);
id(cfg_room_control_ctl).publish_state(((m>>15)&1)!=0);
id(cfg_turbo_dhw_prio_ctl).publish_state((m&1)!=0);
id(mode_party_ctl).publish_state(((m>>6)&1)!=0);
id(mode_vacation_ctl).publish_state(((m>>7)&1)!=0);
id(mode_manual_ctl).publish_state(((m>>9)&1)!=0);
id(mode_turbo_ctl).publish_state(((m>>11)&1)!=0);''',
 "config2_word":'''uint16_t c=(uint16_t)x;
id(cfg_circulation_ctl).publish_state(((c>>2)&1)!=0);
id(cfg_pressure_ctl).publish_state(((c>>8)&1)!=0);
id(cfg_dis_circ_ctl).publish_state(((c>>5)&1)!=0);
id(cfg_dis_now_ctl).publish_state(((c>>6)&1)!=0);
id(cfg_dis_auto_ctl).publish_state(((c>>7)&1)!=0);''',
 "error_code":'''uint16_t e=(uint16_t)x;
if(e==0){ id(error_text).publish_state("OK"); return; }
const char* n[]={"EEPROM","czujnik T wej.","czujnik T wyj.","czujnik T zasobnika","czujnik T wewn.","czujnik T zewn.","czujnik T pokojowej","słaba bateria","ciśnienie","pompa CO","zawór CO","zawór CWU"};
std::string t;
for(int i=0;i<12;i++){ if((e>>i)&1){ if(!t.empty()) t+=", "; t+=n[i]; } }
if(t.empty()) t="Błąd "+std::to_string(e);
id(error_text).publish_state(t);''',
 "power_now":'''id(status_text).publish_state(x>0.3f?"Grzanie":"Bezczynny");''',
 "pump_type_ro":'''int i=(int)x; std::string s=(i==1?"Wilo":"Grundfos");
id(pump_type_text).publish_state(s); id(pump_type_ctl).publish_state(s);''',
 "pump_regulation_ro":'''int i=(int)x; std::string s=(i==1?"constant delta-p":"variable delta-p");
id(pump_reg_text).publish_state(s); id(pump_reg_ctl).publish_state(s);''',
 "pump_lift_ro":'''int i=(int)x; const char* o[]={"3.0","4.0","5.0","6.0","7.0","7.5"};
std::string s=(i>=0&&i<6)?std::string(o[i]):"?";
id(pump_lift_text).publish_state(s+" kPa"); id(pump_lift_ctl).publish_state(s);''',
 "disinfection_day":'''int d=(int)x; const char* dn[]={"Poniedziałek","Wtorek","Środa","Czwartek","Piątek","Sobota","Niedziela"};
id(disinfection_day_text).publish_state((d>=0&&d<7)?std::string(dn[d]):std::string("—"));''',
 "disinfection_start_min":'''int m=(int)x; char b[8]; if(m<0||m>1439){id(disinfection_start_text).publish_state("—");}
else{snprintf(b,sizeof(b),"%02d:%02d",m/60,m%60); id(disinfection_start_text).publish_state(std::string(b));}''',
 "heater_rtc_min":'''int m=(int)x; float hs=id(heater_rtc_hour).state; if(isnan(hs))return;
char b[8]; snprintf(b,sizeof(b),"%02d:%02d",(int)hs,m); id(heater_clock_text).publish_state(std::string(b));''',
}
def onval_block(body):
    lines=["          "+ln for ln in body.strip("\n").split("\n")]
    return "\n    on_value:\n      - lambda: |-\n"+"\n".join(lines)

# read sensor -> control sync (publish the live value to the optimistic control)
SYNC={"room_hysteresis_ro":"room_hysteresis_set","boiler_supply_ro":"boiler_supply_set"}

# ---------- write pending/confirm framework ----------
# A user-set control ARMs a pending slot (target + deadline). Readback syncs are GUARDED:
# while pending, a non-matching device value is suppressed (control keeps the new position);
# a matching value confirms (slot cleared); past the deadline the control reverts to the device
# value and the slot is marked failed (surfaced via the "Zapisy nieudane" text sensor, auto-clear
# 10 min). Guards compare in engineering units; selects/switches compare by index/bool as float.
WP_TIMEOUT_MS = 90000   # heater applies 0x0B55-gated config with up to ~30 s lag + poll cycle
WP = []      # (entity_id, display_name)
WPIDX = {}   # entity_id -> slot index
WP_EPS = {}  # entity_id -> compare tolerance
def wp_reg(ent, name, eps=0.1):
    if ent in WPIDX: return WPIDX[ent]
    WPIDX[ent] = len(WP); WP.append((ent, name)); WP_EPS[ent] = eps
    return WPIDX[ent]

def wp_arm(ent, val_expr):
    i = WPIDX[ent]
    return f"id(wp_target)[{i}]=({val_expr}); id(wp_until)[{i}]=millis()+{WP_TIMEOUT_MS}UL; id(wp_failed)[{i}]=0;"

def wp_pub(ent, nv_expr, pub_stmt):
    i = WPIDX[ent]; eps = WP_EPS[ent]
    return (f"{{ float nv=({nv_expr}); if(id(wp_until)[{i}]!=0){{ "
            f"if(fabsf(nv-id(wp_target)[{i}])<={eps:g}f){{ id(wp_until)[{i}]=0; {pub_stmt} }} "
            f"else if(millis()>id(wp_until)[{i}]){{ id(wp_until)[{i}]=0; id(wp_failed)[{i}]=millis(); {pub_stmt} }} "
            f"}} else {{ {pub_stmt} }} }}")

# GATED numbers: value only persists if the gate register is (re)written in the same burst.
# We do a FRESH read of the gate reg (create_read_command), then write value + echo the gate
# word back UNCHANGED (byte-for-byte) to trigger the heater's config-apply without disturbing
# any status bit. (id,name,value_reg,vmin,vmax,step,scale,unit,gate_reg)
GATED=[
 ("room_hysteresis","Heater room hysteresis",0x0B75,0.1,5,0.1,10,"°C",0x0B55),
 ("boiler_supply","Heater boiler supply temp",0x0B8C,20,85,0.5,10,"°C",0x0B55),
]
def gated_number(idn,name,vreg,vmin,vmax,step,scale,unit,greg):
    u=f'\n    unit_of_measurement: "{unit}"' if unit else ""
    return f'''  - platform: template
    name: "{name}"
    id: {idn}_set
    min_value: {vmin}
    max_value: {vmax}
    step: {step}
    mode: box{u}
    optimistic: true
    set_action:
      - lambda: |-
          if(!id(esp_owns_bus)){{return;}}
          {wp_arm(idn+"_set","x")}
          uint16_t v=(uint16_t)lroundf(x*{scale}.0f);
          uint16_t wireV=((v&0xFF)<<8)|(v>>8);
          auto rd=esphome::modbus_controller::ModbusCommandItem::create_read_command(
              id(heater), esphome::modbus_controller::ModbusRegisterType::HOLDING, 0x{greg:04X}, 1,
              [wireV](esphome::modbus::EntityType, uint16_t, std::span<const uint8_t> d) {{
                if (d.size() < 2) return;
                id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id(heater), 0x{vreg:04X}, 1, {{wireV}}));
                uint16_t gw=(uint16_t)((d[0]<<8)|d[1]);
                id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id(heater), 0x{greg:04X}, 1, {{gw}}));
              }});
          id(heater)->queue_command(rd);'''

# GATED SELECTS: pump config that only applies when pump is in MANUAL (0x0B55 bit8 = 0).
# On set: fresh-read 0x0B55, write the value, then write 0x0B55 with bit8 CLEARED (decode-
# modify-encode; fresh read avoids clobbering heater status bits). (id,name,value_reg,[opts])
GATED_SELECTS=[
 ("pump_type_ctl","Heater pump type",0x0B58,["Grundfos","Wilo"]),
 ("pump_reg_ctl","Heater pump regulation",0x0B82,["variable delta-p","constant delta-p"]),
 ("pump_lift_ctl","Heater pump lift",0x0B83,["3.0","4.0","5.0","6.0","7.0","7.5"]),
]
def gated_select(idn,name,vreg,opts):
    optlist=", ".join('"%s"'%o for o in opts)
    chain="".join(('if' if i==0 else 'else if')+f'(x=="{o}") idx={i}; ' for i,o in enumerate(opts))
    return f'''  - platform: template
    name: "{name}"
    id: {idn}
    optimistic: true
    options: [{optlist}]
    set_action:
      - lambda: |-
          if(!id(esp_owns_bus)){{return;}}
          int idx=0; {chain}
          {wp_arm(idn,"(float)idx")}
          uint16_t v=(uint16_t)idx; uint16_t wireV=((v&0xFF)<<8)|(v>>8);
          auto rd=esphome::modbus_controller::ModbusCommandItem::create_read_command(
              id(heater), esphome::modbus_controller::ModbusRegisterType::HOLDING, 0x0B55, 1,
              [wireV](esphome::modbus::EntityType, uint16_t, std::span<const uint8_t> d) {{
                if (d.size()<2) return;
                id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id(heater), 0x{vreg:04X}, 1, {{wireV}}));
                uint16_t real=(uint16_t)((d[1]<<8)|d[0]); real &= ~(1<<8);
                uint16_t gw=((real&0xFF)<<8)|(real>>8);
                id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id(heater), 0x0B55, 1, {{gw}}));
              }});
          id(heater)->queue_command(rd);'''

def bit_rmw(setbit, bit=8, reg=0x0B55, dev="heater", arm=""):
    op=f"real |= (1<<{bit});" if setbit else f"real &= ~(1<<{bit});"
    return f'''- lambda: |-
          if(!id(esp_owns_bus)){{return;}}
          {arm}
          auto rd=esphome::modbus_controller::ModbusCommandItem::create_read_command(
              id({dev}), esphome::modbus_controller::ModbusRegisterType::HOLDING, 0x{reg:04X}, 1,
              [](esphome::modbus::EntityType, uint16_t, std::span<const uint8_t> d) {{
                if (d.size()<2) return;
                uint16_t real=(uint16_t)((d[1]<<8)|d[0]); {op}
                uint16_t gw=((real&0xFF)<<8)|(real>>8);
                id({dev})->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id({dev}), 0x{reg:04X}, 1, {{gw}}));
              }});
          id({dev})->queue_command(rd);'''

# Config-flag switches (verified bits from the local C.MI app JS). Gated RMW of the config word.
# (id, name, bit, reg, icon). State synced read-only from the config-word diagnostic on_value.
CONFIG_FLAGS=[
  ("cfg_antifrost","Ochrona przeciwmrozowa budynku",12,0x0B55,"mdi:snowflake"),
  ("cfg_co_curve","CO — regulacja wg krzywej",14,0x0B55,"mdi:chart-bell-curve"),
  ("cfg_tank_enable","Zasobnik CWU włączony",4,0x0B55,"mdi:water-boiler"),
  ("cfg_dhw_int","CWU — termostat wewnętrzny",2,0x0B55,"mdi:thermostat"),
  ("cfg_room_int","Regulator pokojowy wewnętrzny",1,0x0B55,"mdi:home-thermometer"),
  ("cfg_room_control","Kontrola temp. pokojowej",15,0x0B55,"mdi:home-thermometer-outline"),
  ("cfg_turbo_dhw_prio","Turbo — priorytet CWU",0,0x0B55,"mdi:rocket-launch"),
  ("cfg_circulation","Cyrkulacja CWU włączona",2,0x0B54,"mdi:pump"),
  ("cfg_pressure","Kontrola ciśnienia",8,0x0B54,"mdi:gauge"),
  ("cfg_dis_circ","Dezynfekcja z cyrkulacją",5,0x0B54,"mdi:pump-outline"),
  ("cfg_dis_now","Dezynfekcja — uruchom teraz",6,0x0B54,"mdi:play"),
  ("cfg_dis_auto","Dezynfekcja automatyczna",7,0x0B54,"mdi:calendar-clock"),
]
def config_flag_switch(idn,name,bit,reg,icon):
    return f'''  - platform: template
    name: "{name}"
    id: {idn}_ctl
    optimistic: true
    restore_mode: DISABLED
    entity_category: config
    icon: {icon}
    turn_on_action:
      {bit_rmw(True,bit,reg,arm=wp_arm(idn+"_ctl","1.0f"))}
    turn_off_action:
      {bit_rmw(False,bit,reg,arm=wp_arm(idn+"_ctl","0.0f"))}'''

# C.MG3 config-word switches (device 0x69, 0x0B54 — SEPARATE from the heater's 0x0B54). Plain RMW
# (no echo/gate). bit1 regulation (0=ręcznie,1=krzywa), bit4 hand, bit5 pump auto. From the local app.
CMG3_FLAGS=[
  ("cmg3_regulation","C.MG3 — regulacja wg krzywej",1,"mdi:chart-bell-curve"),
  ("cmg3_hand","C.MG3 — tryb ręczny",4,"mdi:hand-back-right"),
  ("cmg3_pump_auto","C.MG3 — pompa AUTO",5,"mdi:pump"),
]
def cmg3_flag_switch(idn,name,bit,icon):
    return f'''  - platform: template
    name: "{name}"
    id: {idn}_ctl
    optimistic: true
    restore_mode: DISABLED
    entity_category: config
    icon: {icon}
    turn_on_action:
      {bit_rmw(True,bit,0x0B54,"cmg3",arm=wp_arm(idn+"_ctl","1.0f"))}
    turn_off_action:
      {bit_rmw(False,bit,0x0B54,"cmg3",arm=wp_arm(idn+"_ctl","0.0f"))}'''

# Special-mode switches (from the local C.MI app: activation = 0x0B55 bit + for party/vacation an
# off-time in 0x0B6C). "Until cancel" = 0x0B6C all-zeros. Simple on/off; timed durations are a later
# refinement. 0x0B55 bit-writes DO stick (config flags proved it, ~30s lag).
def timer_mode_on(bit, arm=""):  # party/vacation ON: write 0x0B6C=zeros (until-cancel) + set 0x0B55 bit
    return f'''- lambda: |-
          if(!id(esp_owns_bus)){{return;}}
          {arm}
          auto rd=esphome::modbus_controller::ModbusCommandItem::create_read_command(
              id(heater), esphome::modbus_controller::ModbusRegisterType::HOLDING, 0x0B55, 1,
              [](esphome::modbus::EntityType, uint16_t, std::span<const uint8_t> d) {{
                if (d.size()<2) return;
                id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id(heater), 0x0B6C, 5, {{0,0,0,0,0}}));
                uint16_t real=(uint16_t)((d[1]<<8)|d[0]); real |= (1<<{bit});
                uint16_t gw=((real&0xFF)<<8)|(real>>8);
                id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id(heater), 0x0B55, 1, {{gw}}));
              }});
          id(heater)->queue_command(rd);'''
SPECIAL_MODES=[  # (id, name, bit, icon, timer)
  ("mode_party","Tryb Party",6,"mdi:party-popper",True),
  ("mode_vacation","Tryb Urlop (wakacje)",7,"mdi:bag-suitcase",True),
  ("mode_manual","Tryb ręczny",9,"mdi:hand-back-right",False),
  ("mode_turbo","Tryb Turbo",11,"mdi:rocket-launch",False),
]
def special_mode_switch(idn,name,bit,icon,timer):
    arm_on=wp_arm(idn+"_ctl","1.0f")
    on = timer_mode_on(bit,arm=arm_on) if timer else bit_rmw(True,bit,arm=arm_on)
    return f'''  - platform: template
    name: "{name}"
    id: {idn}_ctl
    optimistic: true
    restore_mode: DISABLED
    icon: {icon}
    turn_on_action:
      {on}
    turn_off_action:
      {bit_rmw(False,bit,arm=wp_arm(idn+"_ctl","0.0f"))}'''
def pump_auto_switch():
    return f'''switch:
  - platform: template
    name: "Heater pump auto"
    id: pump_auto_ctl
    optimistic: true
    restore_mode: DISABLED
    icon: mdi:pump
    turn_on_action:
      {bit_rmw(True,arm=wp_arm("pump_auto_ctl","1.0f"))}
    turn_off_action:
      {bit_rmw(False,arm=wp_arm("pump_auto_ctl","0.0f"))}'''

# Relays 5 & 6 (PCF8574 pins 4 & 5) break the C.MI's RS485 A & B. "Bus owner: C.MI" hands the
# bus over safely: ESP goes silent FIRST, pause, then relays close; reverse on the way back.
BUS_SWITCH='''  - platform: gpio
    name: "C.MI relay A (RS485 A)"
    id: relay_cmi_a
    entity_category: config
    restore_mode: ALWAYS_OFF
    pin: { pcf8574: pcf_out, number: 4, mode: { output: true }, inverted: true }
  - platform: gpio
    name: "C.MI relay B (RS485 B)"
    id: relay_cmi_b
    entity_category: config
    restore_mode: ALWAYS_OFF
    pin: { pcf8574: pcf_out, number: 5, mode: { output: true }, inverted: true }
  - platform: template
    name: "Bus owner: C.MI (diagnostics)"
    id: bus_give_cmi
    icon: mdi:swap-horizontal
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      - lambda: |-
          id(esp_owns_bus) = false;          // stop heartbeat + block writes
          id(heater)->stop_poller();          // stop auto reads
          id(cmg3)->stop_poller();
      - delay: 800ms
      - switch.turn_on: relay_cmi_a
      - switch.turn_on: relay_cmi_b
      - logger.log: "Bus handed to C.MI; ESP is passive."
    turn_off_action:
      - switch.turn_off: relay_cmi_a
      - switch.turn_off: relay_cmi_b
      - delay: 800ms
      - lambda: |-
          id(esp_owns_bus) = true;
          id(heater)->start_poller();
          id(cmg3)->start_poller();
      - logger.log: "Bus reclaimed by ESP master."'''

# ---- register every writable control in the pending framework (indices used by guards below) ----
for dev,reg,idn,name,vmin,vmax,step,scale,unit in CONTROLS: wp_reg(idn+"_set", name, step/2+0.011)
for idn,name,vreg,vmin,vmax,step,scale,unit,greg in GATED: wp_reg(idn+"_set", name, step/2+0.011)
for dev,reg,idn,name,opts in SELECTS: wp_reg(idn+"_set", name)
wp_reg("heater_mode","Tryb sezonu (Zima/Lato)")
for idn,name,vreg,opts in GATED_SELECTS: wp_reg(idn, name)
wp_reg("pump_auto_ctl","Heater pump auto")
for idn,name,bit,reg,icon in CONFIG_FLAGS: wp_reg(idn+"_ctl", name)
for idn,name,bit,icon,timer in SPECIAL_MODES: wp_reg(idn+"_ctl", name)
for idn,name,bit,icon in CMG3_FLAGS: wp_reg(idn+"_ctl", name)
assert len(WP) <= 96, f"raise wp_* array size: {len(WP)} controls"

# guard the switch syncs inside the TEXTHOOKS (id(*_ctl).publish_state(<bit expr>);)
import re as _re
def _wp_guard_ctl(m):
    ent, expr = m.group(1), m.group(2)
    if ent not in WPIDX: return m.group(0)
    return wp_pub(ent, f"(({expr})?1.0f:0.0f)", f"id({ent}).publish_state(nv>0.5f);")
for _k in ("mode_word","config2_word"):
    TEXTHOOKS[_k]=_re.sub(r"id\((\w+_ctl)\)\.publish_state\((.+?)\);", _wp_guard_ctl, TEXTHOOKS[_k])
# pump selects sync by option index (var i exists in those hooks); string publish kept as-is inside
for _k,_e in (("pump_type_ro","pump_type_ctl"),("pump_regulation_ro","pump_reg_ctl"),("pump_lift_ro","pump_lift_ctl")):
    TEXTHOOKS[_k]=TEXTHOOKS[_k].replace(f"id({_e}).publish_state(s);", wp_pub(_e,"(float)i",f"id({_e}).publish_state(s);"))
# heater_mode select sync (off=0, summer=1, winter=2 — matches its options order)
TEXTHOOKS["mode_word"]=TEXTHOOKS["mode_word"].replace(
 '''if ((m>>5)&1) id(heater_mode).publish_state("winter");
else if ((m>>3)&1) id(heater_mode).publish_state("summer");
else id(heater_mode).publish_state("off");''',
 wp_pub("heater_mode","((m>>5)&1)?2.0f:(((m>>3)&1)?1.0f:0.0f)",
        'id(heater_mode).publish_state(nv>1.5f?"winter":(nv>0.5f?"summer":"off"));'))

out=[HEAD, "sensor:"]
for reg,idn,name,scale,fault,unit,dclass in MON:
    s=f"""  - platform: modbus_controller
    modbus_controller_id: heater
    id: {idn}
    name: "{name}"
    register_type: holding
    address: 0x{reg:04X}
    value_type: U_WORD"""
    if unit: s+=f'\n    unit_of_measurement: "{unit}"'
    if dclass: s+=f'\n    device_class: {dclass}'
    s+="\n    state_class: measurement"
    s+=f"\n    filters:\n      {swap_signed(scale,fault)}"
    # drop transient fault reads (NaN) so HA keeps the last good value instead of going unavailable
    if fault: s+="\n      - filter_out: nan"
    if idn in TEXTHOOKS: s+=onval_block(TEXTHOOKS[idn])
    elif idn in SYNC: s+=onval_block(wp_pub(SYNC[idn],"x",f"id({SYNC[idn]}).publish_state(x);"))
    out.append(s)
for reg,idn,name in RAWDIAG:
    s=f"""  - platform: modbus_controller
    modbus_controller_id: heater
    id: {idn}
    name: "{name}"
    register_type: holding
    address: 0x{reg:04X}
    value_type: U_WORD
    entity_category: diagnostic
    filters:
      {swap_uint()}"""
    if idn in TEXTHOOKS: s+=onval_block(TEXTHOOKS[idn])
    out.append(s)
# C.MG3 read-only diagnostic (config/flags word). The writable C.MG3 controls (curve number/
# shift, max supply, hand temp, regulation) are generated from CONTROLS/SELECTS below.
out.append(f"""  - platform: modbus_controller
    modbus_controller_id: cmg3
    id: cmg3_config_word
    name: "C.MG3 config word"
    register_type: holding
    address: 0x0B54
    value_type: U_WORD
    entity_category: diagnostic
    force_new_range: true
    filters:
      {swap_uint()}
    on_value:
      - lambda: |-
          uint16_t c=(uint16_t)x;
          {wp_pub("cmg3_regulation_ctl","(((c>>1)&1)!=0)?1.0f:0.0f","id(cmg3_regulation_ctl).publish_state(nv>0.5f);")}
          {wp_pub("cmg3_hand_ctl","(((c>>4)&1)!=0)?1.0f:0.0f","id(cmg3_hand_ctl).publish_state(nv>0.5f);")}
          {wp_pub("cmg3_pump_auto_ctl","(((c>>5)&1)!=0)?1.0f:0.0f","id(cmg3_pump_auto_ctl).publish_state(nv>0.5f);")}""")
for dev,reg,idn,name,vmin,vmax,step,scale,unit in CONTROLS:
    sc=1.0/scale if scale!=1 else 1.0
    s=f"""  - platform: modbus_controller
    modbus_controller_id: {dev}
    id: {idn}_read
    name: "{name} (read)"
    register_type: holding
    address: 0x{reg:04X}
    value_type: U_WORD
    entity_category: diagnostic"""
    if dev=="cmg3": s+="\n    force_new_range: true"   # C.MG3 rejects wide coalesced reads
    if unit: s+=f'\n    unit_of_measurement: "{unit}"'
    s+=f"\n    filters:\n      {swap_signed(sc,False)}"
    # sync the writable control to the live device value (publish_state does NOT fire set_action),
    # guarded by the pending framework (no snap-back while a write is in flight)
    s+="\n    on_value:\n      - lambda: |-\n          "+wp_pub(f"{idn}_set","x",f"id({idn}_set).publish_state(x);")
    out.append(s)
for dev,reg,idn,name,opts in SELECTS:
    s=f"""  - platform: modbus_controller
    modbus_controller_id: {dev}
    id: {idn}_read
    name: "{name} (read)"
    register_type: holding
    address: 0x{reg:04X}
    value_type: U_WORD
    entity_category: diagnostic{chr(10)+'    force_new_range: true' if dev=='cmg3' else ''}
    filters:
      {swap_uint()}"""
    chain="".join(('if' if i==0 else 'else if')+f'(i=={i}) id({idn}_set).publish_state("{o}"); ' for i,o in enumerate(opts))
    guarded=wp_pub(f"{idn}_set","(float)i","pub();")
    s+=f"\n    on_value:\n      - lambda: |-\n          int i=(int)x; auto pub=[&](){{ {chain} }}; {guarded}"
    out.append(s)

# TRV bridge readbacks (visible in HA too, but sourced HA-independently via the GPU-box bridge)
out.append('''  - platform: template
    name: "TRV okna otwarte (ESP)"
    accuracy_decimals: 0
    update_interval: 60s
    lambda: 'return (id(trv_okna) < 0) ? NAN : (float) id(trv_okna);'
  - platform: template
    name: "TRV najzimniejszy pokój (ESP)"
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1
    update_interval: 60s
    lambda: 'return id(trv_min_temp);'
  - platform: wifi_signal
    name: "WiFi RSSI"
    update_interval: 60s''')

out.append("text_sensor:")
for idn,name in TEXT_SENSORS:
    out.append(f"""  - platform: template
    id: {idn}
    name: "{name}\"""")
# Schedule editor: read-only preview of the loaded program's 5 slots (populated by "Wczytaj").
for i in range(1,6):
    out.append(f"""  - platform: template
    id: sched_view{i}
    name: "Podgląd: przedział {i}"
    icon: mdi:clock-check-outline
    entity_category: diagnostic""")

out.append("binary_sensor:")
for name,bit in STATUS_BITS:
    out.append(f"""  - platform: template
    name: "Heater {name}"
    lambda: 'return ((uint16_t) id(status_word).state) & (1 << {bit});'""")
for name,bit in MODE_BITS:
    out.append(f"""  - platform: template
    name: "Heater mode {name}"
    lambda: 'return ((uint16_t) id(mode_word).state) & (1 << {bit});'""")
# Anti-legionella running indicator: DHW driven well above its normal comfort setpoint (max ~48C)
# toward the disinfection target (~70C). Derived, no dedicated status bit needed.
out.append("""  - platform: template
    name: "Dezynfekcja aktywna"
    id: disinfection_active
    device_class: running
    lambda: |-
      if (isnan(id(dhw_temp).state)) return {};
      return id(dhw_temp).state > 52.0;""")
# Alarm: heater error word (0x0B52) non-zero. Details in the "Heater error" text sensor.
out.append("""  - platform: template
    name: "Heater alarm"
    device_class: problem
    lambda: |-
      // NaN before the first modbus read (boot) casts to garbage -> false alarms on every reboot
      if (isnan(id(error_code).state)) return {};
      return ((uint16_t) id(error_code).state) != 0;""")
out.append("""  - platform: template
    name: "TRV failsafe Lato (ESP)"
    icon: mdi:window-open-variant
    lambda: 'return id(trv_lato_flag);'""")

# Controls whose value only persists if the device's flag word is (re)written in the same burst.
# {control_id: gate_reg} — curve/config registers latch only when the config word is (re)written in
# the same burst (echo 0x0B55, like room hysteresis 0x0B75). Plain writes to these revert.
GATE_MAP={"co_curve_offset":0x0B55, "co_curve_number":0x0B55,
          "cmg3_curve_number":0x0B54, "cmg3_curve_shift":0x0B54}
out.append("number:")
for dev,reg,idn,name,vmin,vmax,step,scale,unit in CONTROLS:
    conv = "uint16_t v=(uint16_t)x;" if scale==1 else f"uint16_t v=(uint16_t)lroundf(x*{scale}.0f);"
    u = f'\n    unit_of_measurement: "{unit}"' if unit else ""
    if idn in GATE_MAP:
        greg=GATE_MAP[idn]
        act=f"""      - lambda: |-
          if(!id(esp_owns_bus)){{return;}}
          {wp_arm(idn+"_set","x")}
          {conv} uint16_t wireV=((v&0xFF)<<8)|(v>>8);
          auto rd=esphome::modbus_controller::ModbusCommandItem::create_read_command(
              id({dev}), esphome::modbus_controller::ModbusRegisterType::HOLDING, 0x{greg:04X}, 1,
              [wireV](esphome::modbus::EntityType, uint16_t, std::span<const uint8_t> d) {{
                if (d.size()<2) return;
                id({dev})->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id({dev}), 0x{reg:04X}, 1, {{wireV}}));
                uint16_t gw=(uint16_t)((d[0]<<8)|d[1]);
                id({dev})->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    id({dev}), 0x{greg:04X}, 1, {{gw}}));
              }});
          id({dev})->queue_command(rd);"""
    else:
        act=f"""      - lambda: |-
          if(!id(esp_owns_bus)){{return;}}
          {wp_arm(idn+"_set","x")}
          {conv} uint16_t wire=((v&0xFF)<<8)|(v>>8);
          auto cmd=esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              id({dev}), 0x{reg:04X}, 1, {{wire}});
          id({dev})->queue_command(cmd);"""
    out.append(f"""  - platform: template
    name: "{name}"
    id: {idn}_set
    min_value: {vmin}
    max_value: {vmax}
    step: {step}
    mode: box{u}
    optimistic: true
    set_action:
{act}""")
for g in GATED:
    out.append(gated_number(*g))
# Schedule editor: which program number (1-8) to load/edit/save.
out.append('''  - platform: template
    name: "Edytor: numer programu"
    id: sched_prog
    optimistic: true
    min_value: 1
    max_value: 8
    step: 1
    initial_value: 1
    mode: box
    icon: mdi:numeric
    entity_category: config''')


out.append("select:")
for dev,reg,idn,name,opts in SELECTS:
    optlist=", ".join('"%s"'%o for o in opts)
    chain="".join(('if' if i==0 else 'else if')+f' (x=="{o}") idx={i}; ' for i,o in enumerate(opts))
    out.append(f"""  - platform: template
    name: "{name}"
    id: {idn}_set
    optimistic: true
    options: [{optlist}]
    set_action:
      - lambda: |-
          if(!id(esp_owns_bus)){{return;}}
          int idx=0; {chain}
          {wp_arm(idn+"_set","(float)idx")}
          uint16_t v=(uint16_t)idx; uint16_t wire=((v&0xFF)<<8)|(v>>8);
          auto cmd=esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              id({dev}), 0x{reg:04X}, 1, {{wire}});
          id({dev})->queue_command(cmd);""")
out.append('''  - platform: template
    name: "Heater mode"
    id: heater_mode
    options: ["off", "summer", "winter"]
    optimistic: true
    set_action:
      - lambda: |-
          if(!id(esp_owns_bus)){return;}
          ''' + wp_arm("heater_mode",'(x=="winter")?2.0f:((x=="summer")?1.0f:0.0f)') + '''
          uint16_t reg=(uint16_t)id(mode_word).state;
          reg &= ~((1<<3)|(1<<5));
          if (x=="summer") reg|=(1<<3);
          if (x=="winter") reg|=(1<<5);
          uint16_t wire=((reg&0xFF)<<8)|(reg>>8);
          auto cmd=esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              id(heater), 0x0B55, 1, {wire});
          id(heater)->queue_command(cmd);''')
# Schedule editor: timetable selector + 5 slot temperature-level selects.
out.append('''  - platform: template
    name: "Edytor: harmonogram"
    id: sched_tt
    optimistic: true
    options: ["CO", "CWU", "Cyrkulacja", "C.MG3"]
    initial_option: "CO"
    icon: mdi:calendar-edit
    entity_category: config''')
for i in range(1,6):
    out.append(f'''  - platform: template
    name: "Edytor: poziom {i}"
    id: sched_lvl{i}
    optimistic: true
    options: ["—", "Ochrona", "Komfort", "Komfort−", "Komfort+"]
    initial_option: "—"
    icon: mdi:thermometer
    entity_category: config''')
for g in GATED_SELECTS:
    out.append(gated_select(*g))
out.append(pump_auto_switch())
for cf in CONFIG_FLAGS:
    out.append(config_flag_switch(*cf))
for sm in SPECIAL_MODES:
    out.append(special_mode_switch(*sm))
for cf in CMG3_FLAGS:
    out.append(cmg3_flag_switch(*cf))
out.append(BUS_SWITCH)

if BITS:
    out.append("switch:")
for reg,bit,idn,name,base in BITS:
    out.append(f"""  - platform: template
    name: "{name}"
    id: sw_{idn}
    optimistic: true
    restore_mode: DISABLED
    turn_on_action:
      - lambda: |-
          uint16_t r=(uint16_t)id({base}).state; r |= (1 << {bit});
          uint16_t wire=((r&0xFF)<<8)|(r>>8);
          auto cmd=esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              id(heater), 0x{reg:04X}, 1, {{wire}});
          id(heater)->queue_command(cmd);
    turn_off_action:
      - lambda: |-
          uint16_t r=(uint16_t)id({base}).state; r &= ~(1 << {bit});
          uint16_t wire=((r&0xFF)<<8)|(r>>8);
          auto cmd=esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              id(heater), 0x{reg:04X}, 1, {{wire}});
          id(heater)->queue_command(cmd);""")

# Schedule editor: 5 time-slot text fields ("HH:MM-HH:MM", empty = przedział pusty).
out.append("text:")
for i in range(1,6):
    out.append(f'''  - platform: template
    name: "Edytor: przedział {i}"
    id: sched_slot{i}
    optimistic: true
    mode: text
    min_length: 0
    max_length: 11
    initial_value: ""
    icon: mdi:clock-outline
    entity_category: config''')

# Schedule editor: Load reads the selected program's 15-reg block into the editor entities;
# Save parses them back and writes the block. Base = {CO 0x0C1C, CWU 0x0C9E, cyrk 0x0D20, C.MG3
# 0x0B90}[timetable] + 15*(nr-1); C.MG3 lives on the cmg3 device, the other three on the heater.
_SLOTS='esphome::text::Text* slots[5]={id(sched_slot1),id(sched_slot2),id(sched_slot3),id(sched_slot4),id(sched_slot5)};'
_LVLS='esphome::select::Select* lvls[5]={id(sched_lvl1),id(sched_lvl2),id(sched_lvl3),id(sched_lvl4),id(sched_lvl5)};'
out.append('''button:
  # On-demand WiFi site survey: blocking all-channel scan (~2 s loop stall, diagnostic use),
  # full list to the log at INFO, compact strongest-first summary into the "Skan WiFi" sensor.
  - platform: template
    name: "Skan sieci WiFi"
    id: wifi_scan_btn
    icon: mdi:wifi-refresh
    entity_category: diagnostic
    on_press:
      - lambda: |-
          wifi_scan_config_t sc{};
          sc.show_hidden = true;
          if (esp_wifi_scan_start(&sc, true) != ESP_OK) { id(wifi_scan_result).publish_state("scan start failed"); return; }
          uint16_t n = 20; static wifi_ap_record_t recs[20];
          if (esp_wifi_scan_get_ap_records(&n, recs) != ESP_OK) { id(wifi_scan_result).publish_state("scan read failed"); return; }
          for (int i=0;i<n;i++) for (int j=i+1;j<n;j++) if (recs[j].rssi > recs[i].rssi) std::swap(recs[i], recs[j]);
          std::string out;
          for (int i=0;i<n;i++) {
            char b[80];
            ESP_LOGI("wifiscan", "%s %02X:%02X:%02X:%02X:%02X:%02X ch%u %d dBm",
                     (const char*)recs[i].ssid, recs[i].bssid[0], recs[i].bssid[1], recs[i].bssid[2],
                     recs[i].bssid[3], recs[i].bssid[4], recs[i].bssid[5], recs[i].primary, recs[i].rssi);
            snprintf(b, sizeof(b), "%s|%02X%02X ch%u %d; ", (const char*)recs[i].ssid,
                     recs[i].bssid[4], recs[i].bssid[5], recs[i].primary, recs[i].rssi);
            if (out.size() + strlen(b) < 250) out += b;
          }
          if (out.empty()) out = "brak sieci";
          id(wifi_scan_result).publish_state(out);''')
out.append(f'''  - platform: template
    name: "Edytor: wczytaj program"
    id: sched_load
    icon: mdi:download
    entity_category: config
    on_press:
      - lambda: |-
          if(!id(esp_owns_bus)) return;
          int tt=id(sched_tt).active_index().value_or(0);
          int prog=(int)id(sched_prog).state; if(prog<1)prog=1; if(prog>8)prog=8;
          static const uint16_t bases[4]={{0x0C1C,0x0C9E,0x0D20,0x0B90}};
          uint16_t base=(uint16_t)(bases[tt]+15*(prog-1));
          auto cb=[](esphome::modbus::EntityType, uint16_t, std::span<const uint8_t> d){{
            if(d.size()<30) return;
            esphome::text_sensor::TextSensor* view[5]={{id(sched_view1),id(sched_view2),id(sched_view3),id(sched_view4),id(sched_view5)}};
            {_SLOTS}
            {_LVLS}
            static const char* lo[5]={{"—","Ochrona","Komfort","Komfort−","Komfort+"}};
            auto R=[&](int r){{ return (uint16_t)((d[2*r+1]<<8)|d[2*r]); }};
            for(int s=0;s<5;s++){{
              uint16_t start=R(2*s), stop=R(2*s+1), lv=R(10+s);
              int li=(lv>=1&&lv<=4)?(int)lv:0;
              char buf[48];
              if(start>1439||stop>1439){{ snprintf(buf,sizeof(buf),"— (pusty)"); slots[s]->make_call().set_value("").perform(); }}
              else {{ snprintf(buf,sizeof(buf),"%02d:%02d-%02d:%02d · %s",start/60,start%60,stop/60,stop%60,lo[li]); char t[12]; snprintf(t,sizeof(t),"%02d:%02d-%02d:%02d",start/60,start%60,stop/60,stop%60); slots[s]->make_call().set_value(std::string(t)).perform(); }}
              view[s]->publish_state(buf);
              lvls[s]->publish_state(lo[li]);
            }}
          }};
          if(tt==3) id(cmg3)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_read_command(id(cmg3),esphome::modbus_controller::ModbusRegisterType::HOLDING,base,15,cb));
          else id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_read_command(id(heater),esphome::modbus_controller::ModbusRegisterType::HOLDING,base,15,cb));
  - platform: template
    name: "Edytor: zapisz program"
    id: sched_save
    icon: mdi:content-save
    entity_category: config
    on_press:
      - lambda: |-
          if(!id(esp_owns_bus)) return;
          int tt=id(sched_tt).active_index().value_or(0);
          int prog=(int)id(sched_prog).state; if(prog<1)prog=1; if(prog>8)prog=8;
          static const uint16_t bases[4]={{0x0C1C,0x0C9E,0x0D20,0x0B90}};
          uint16_t base=(uint16_t)(bases[tt]+15*(prog-1));
          {_SLOTS}
          {_LVLS}
          auto sw=[](uint16_t v){{return (uint16_t)(((v&0xFF)<<8)|(v>>8));}};
          uint16_t st[5],sp[5],lv[5];
          for(int s=0;s<5;s++){{
            std::string t=slots[s]->state; int h1,m1,h2,m2;
            if(sscanf(t.c_str(),"%d:%d-%d:%d",&h1,&m1,&h2,&m2)==4 && h1>=0&&h1<24&&m1>=0&&m1<60&&h2>=0&&h2<24&&m2>=0&&m2<60){{ st[s]=(uint16_t)(h1*60+m1); sp[s]=(uint16_t)(h2*60+m2); }}
            else {{ st[s]=65535; sp[s]=65535; }}
            int li=lvls[s]->active_index().value_or(0); lv[s]=(li>=1&&li<=4)?(uint16_t)li:65535;
          }}
          std::vector<uint16_t> regs;
          for(int s=0;s<5;s++){{ regs.push_back(sw(st[s])); regs.push_back(sw(sp[s])); }}
          for(int s=0;s<5;s++) regs.push_back(sw(lv[s]));
          if(tt==3) id(cmg3)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(id(cmg3),base,15,regs));
          else id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(id(heater),base,15,regs));''')

# TRV-bridge poll + HA-independent window failsafe. Data path: zwave-js (RPi) -> trv_bridge
# (r730-gpu:8901) -> this ESP. Rule mirrors the HA "wietrzenie" automation so it works with HA down:
# >=2 windows open 3 min in Zima -> Lato (CWU keeps working); all closed 2 min -> restore Zima.
# Acts only on FRESH data (<10 min) and only reverses what it itself changed (trv_lato_flag).
out.append('''interval:
  - interval: 30s
    then:
      - lambda: |-
          if (!id(esp_owns_bus)) return;
          uint32_t now = millis();
          if (id(trv_last_ok) == 0 || now - id(trv_last_ok) > 10UL*60UL*1000UL) return;  // stale data
          uint16_t m = (uint16_t) id(mode_word).state;
          bool winter = (m >> 5) & 1, summer = (m >> 3) & 1;
          int okna = id(trv_okna);
          if (okna >= 2 && winter) { if (id(trv_okna_since) == 0) id(trv_okna_since) = now; }
          else id(trv_okna_since) = 0;
          if (okna == 0) { if (id(trv_closed_since) == 0) id(trv_closed_since) = now; }
          else id(trv_closed_since) = 0;
          auto rmw_season = [](bool to_summer){
            auto rd = esphome::modbus_controller::ModbusCommandItem::create_read_command(
                id(heater), esphome::modbus_controller::ModbusRegisterType::HOLDING, 0x0B55, 1,
                [to_summer](esphome::modbus::EntityType, uint16_t, std::span<const uint8_t> d) {
                  if (d.size() < 2) return;
                  uint16_t real = (uint16_t)((d[1] << 8) | d[0]);
                  if (to_summer) { real |= (1 << 3); real &= ~(1 << 5); }
                  else { real &= ~(1 << 3); real |= (1 << 5); }
                  uint16_t gw = ((real & 0xFF) << 8) | (real >> 8);
                  id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                      id(heater), 0x0B55, 1, {gw}));
                });
            id(heater)->queue_command(rd);
          };
          if (!id(trv_lato_flag) && winter && id(trv_okna_since) != 0 && now - id(trv_okna_since) > 3UL*60UL*1000UL) {
            rmw_season(true); id(trv_lato_flag) = true;
            ESP_LOGW("trv", "Failsafe: okna otwarte -> Lato (CO wstrzymane)");
          }
          if (id(trv_lato_flag) && summer && id(trv_closed_since) != 0 && now - id(trv_closed_since) > 2UL*60UL*1000UL) {
            rmw_season(false); id(trv_lato_flag) = false;
            ESP_LOGW("trv", "Failsafe: okna zamkniete -> Zima (CO wznowione)");
          }
  # Power-plan executor: hourly max-power cap with LOCAL guards. Runs entirely on the ESP so it
  # survives an HA outage. Guards force FULL power: room near the comfort floor, tank below
  # cwu_min (heavy hot-water usage mid-peak -> recover, then re-cap), disinfection (>52C).
  # Plan older than 26 h = stale -> one-time restore to full power and stop steering.
  - interval: 300s
    then:
      - lambda: |-
          if (!id(esp_owns_bus) || !id(pwr_enable)) return;
          uint32_t now = millis();
          bool stale = (id(pwr_last) == 0) || (now - id(pwr_last) > 93600000UL);
          auto t = id(sntp_time).now();
          int target = 3;
          if (!stale && t.is_valid()) {
            target = id(pwr_plan)[t.hour];
            if (target < 0 || target > 3) target = 3;
            float room = id(room_temp).state, dhw = id(dhw_temp).state;
            if (!isnan(room) && room < id(pwr_floor) + 0.5f) target = 3;
            if (!isnan(dhw) && dhw < id(pwr_cwu_min)) target = 3;
            if (!isnan(dhw) && dhw > 52.0f) target = 3;
          }
          if (stale) { id(pwr_enable) = false; ESP_LOGW("pwrplan", "plan stale -> full power, steering off"); }
          float curf = id(max_power_index_read).state;
          if (!isnan(curf) && (int) curf == target) return;
          uint16_t v = (uint16_t) target, wire = ((v & 0xFF) << 8) | (v >> 8);
          id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              id(heater), 0x0B62, 1, {wire}));
          ESP_LOGI("pwrplan", "max power -> idx %d (hour %d)", target, t.is_valid() ? t.hour : -1);
  - interval: 10s
    then:
      - lambda: |-
          if (!id(esp_owns_bus)) return;   // ESP silent while the C.MI owns the bus
          auto cmd=esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
              id(heater), 0x0BAE, 2, {0x0000, 0x0100});
          id(heater)->queue_command(cmd);  // C.MI-style heartbeat
  - interval: 1h
    then:
      - lambda: |-
          if(!id(esp_owns_bus)) return;
          auto t=id(sntp_time).now(); if(!t.is_valid()) return;
          auto sw=[](uint16_t v){return (uint16_t)(((v&0xFF)<<8)|(v>>8));};
          uint16_t dow=(uint16_t)(((int)t.day_of_week+5)%7);
          std::vector<uint16_t> w={sw((uint16_t)t.second),sw((uint16_t)t.minute),sw((uint16_t)t.hour),sw(dow),sw((uint16_t)t.day_of_month),sw((uint16_t)t.month),sw((uint16_t)(t.year-2000))};
          id(heater)->queue_command(esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(id(heater),0x0AF6,7,w));''')

# Pending-write sweep: expire overdue slots into "failed", publish aggregate text sensors
# (yellow/red banners on the dashboard key off these). Failed entries auto-clear after 10 min.
_wpnames=", ".join('"%s"'%n.replace('"',"'") for _,n in WP)
out.append(f'''  - interval: 5s
    then:
      - lambda: |-
          static const char* WPN[{len(WP)}] = {{{_wpnames}}};
          uint32_t now=millis(); std::string p, f;
          for (int i=0;i<{len(WP)};i++) {{
            if (id(wp_until)[i]!=0) {{
              if (now>id(wp_until)[i]) {{ id(wp_until)[i]=0; id(wp_failed)[i]=now; }}
              else {{ if(!p.empty())p+=", "; p+=WPN[i]; }}
            }}
            if (id(wp_failed)[i]!=0) {{
              if (now-id(wp_failed)[i] > 600000UL) id(wp_failed)[i]=0;
              else {{ if(!f.empty())f+=", "; f+=WPN[i]; }}
            }}
          }}
          if (!id(wp_pending_text).has_state() || p != id(wp_pending_text).state) id(wp_pending_text).publish_state(p);
          if (!id(wp_failed_text).has_state() || f != id(wp_failed_text).state) id(wp_failed_text).publish_state(f);''')

open("kc868-a6-heater-master.yaml","w").write("\n".join(out)+"\n")
print(f"generated: {len(CONTROLS)} numbers, {len(SELECTS)} selects")
